package com.xpllyn.utils.im;

public enum ChatType {

    REGISTER, SINGLE_SENDING, GROUP_SENDING, GROUP_SENDING_All, FILE_MSG_SINGLE_SENDING, FILE_MSG_GROUP_SENDING,
    OFFLINE_NOTIFY, AGREE_FRIEND_REQUEST, READ_REPLY_SENDING;

}
